export const generateDocsHTML = (productDocs, aiDocs) => {
  const parts = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <meta name="description" content="Fashion Redemption Product API Documentation — Secure integration endpoints for chatbots, storefronts, and external applications.">',
    '  <title>Fashion Redemption | API Documentation</title>',
    '  <link rel="preconnect" href="https://fonts.googleapis.com">',
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '  <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,300;0,14..32,400;0,14..32,500;0,14..32,600;0,14..32,700;1,14..32,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">',
    '  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>',
    '  <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-one-dark.min.css" rel="stylesheet">',
    '  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>',
    '  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-json.min.js"></script>',
    '  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-bash.min.js"></script>',
    '  <style>',

    // ── Variables ──────────────────────────────────────────────────────────
    '    :root {',
    '      --bg:           #080b14;',
    '      --surface:      #0e1220;',
    '      --surface-2:    #141929;',
    '      --border:       #1f2d48;',
    '      --border-soft:  #162035;',
    '      --primary:      #7c6aff;',
    '      --primary-glow: rgba(124,106,255,.25);',
    '      --accent:       #c084fc;',
    '      --text:         #e2e8f0;',
    '      --text-muted:   #64748b;',
    '      --text-dim:     #94a3b8;',
    '      --get:          #38bdf8;',
    '      --get-bg:       rgba(56,189,248,.12);',
    '      --post:         #4ade80;',
    '      --post-bg:      rgba(74,222,128,.12);',
    '      --sidebar-w:    280px;',
    '      --radius:       10px;',
    '      --code-bg:      #0d1117;',
    '    }',

    // ── Reset ──────────────────────────────────────────────────────────────
    '    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
    '    html { scroll-behavior: smooth; }',

    // ── Body ───────────────────────────────────────────────────────────────
    '    body {',
    '      font-family: "Inter", system-ui, sans-serif;',
    '      background: var(--bg);',
    '      color: var(--text);',
    '      line-height: 1.7;',
    '      display: flex;',
    '      min-height: 100vh;',
    '      overflow-x: hidden;',
    '    }',

    // ── Sidebar ────────────────────────────────────────────────────────────
    '    aside {',
    '      width: var(--sidebar-w);',
    '      background: var(--surface);',
    '      border-right: 1px solid var(--border);',
    '      padding: 0;',
    '      position: fixed;',
    '      top: 0; left: 0;',
    '      height: 100vh;',
    '      overflow-y: auto;',
    '      z-index: 200;',
    '      display: flex;',
    '      flex-direction: column;',
    '      scrollbar-width: thin;',
    '      scrollbar-color: var(--border) transparent;',
    '    }',

    '    .sidebar-header {',
    '      padding: 1.75rem 1.5rem 1.25rem;',
    '      border-bottom: 1px solid var(--border-soft);',
    '      position: sticky;',
    '      top: 0;',
    '      background: var(--surface);',
    '      z-index: 10;',
    '    }',

    '    .brand {',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 0.6rem;',
    '      margin-bottom: 1rem;',
    '    }',

    '    .brand-icon {',
    '      width: 32px; height: 32px;',
    '      background: linear-gradient(135deg, var(--primary), var(--accent));',
    '      border-radius: 8px;',
    '      display: flex;',
    '      align-items: center;',
    '      justify-content: center;',
    '      font-size: 16px;',
    '      flex-shrink: 0;',
    '    }',

    '    .brand-name {',
    '      font-size: 0.9rem;',
    '      font-weight: 700;',
    '      background: linear-gradient(90deg, #a78bfa, #c084fc);',
    '      -webkit-background-clip: text;',
    '      -webkit-text-fill-color: transparent;',
    '      letter-spacing: -0.01em;',
    '    }',

    '    .brand-sub {',
    '      font-size: 0.7rem;',
    '      color: var(--text-muted);',
    '      font-weight: 400;',
    '    }',

    '    .version-badge {',
    '      display: inline-flex;',
    '      align-items: center;',
    '      gap: 0.35rem;',
    '      padding: 0.2rem 0.6rem;',
    '      background: rgba(124,106,255,.15);',
    '      border: 1px solid rgba(124,106,255,.3);',
    '      border-radius: 999px;',
    '      font-size: 0.65rem;',
    '      font-weight: 600;',
    '      color: var(--primary);',
    '      letter-spacing: 0.04em;',
    '      text-transform: uppercase;',
    '    }',

    '    .version-dot {',
    '      width: 5px; height: 5px;',
    '      background: #4ade80;',
    '      border-radius: 50%;',
    '      animation: pulse 2s infinite;',
    '    }',

    '    @keyframes pulse {',
    '      0%,100% { opacity: 1; }',
    '      50%      { opacity: 0.3; }',
    '    }',

    // Search
    '    .sidebar-search {',
    '      padding: 0.85rem 1.5rem;',
    '      border-bottom: 1px solid var(--border-soft);',
    '    }',

    '    .search-box {',
    '      position: relative;',
    '    }',

    '    .search-box input {',
    '      width: 100%;',
    '      background: var(--surface-2);',
    '      border: 1px solid var(--border);',
    '      border-radius: 8px;',
    '      padding: 0.5rem 0.75rem 0.5rem 2rem;',
    '      color: var(--text);',
    '      font-size: 0.8rem;',
    '      font-family: inherit;',
    '      outline: none;',
    '      transition: border-color .2s, box-shadow .2s;',
    '    }',

    '    .search-box input:focus {',
    '      border-color: var(--primary);',
    '      box-shadow: 0 0 0 3px var(--primary-glow);',
    '    }',

    '    .search-box input::placeholder { color: var(--text-muted); }',

    '    .search-icon {',
    '      position: absolute;',
    '      left: 0.6rem; top: 50%;',
    '      transform: translateY(-50%);',
    '      color: var(--text-muted);',
    '      font-size: 0.75rem;',
    '      pointer-events: none;',
    '    }',

    // Nav
    '    .sidebar-nav { padding: 1rem 1.5rem 2rem; flex: 1; }',

    '    .nav-group-label {',
    '      font-size: 0.65rem;',
    '      font-weight: 700;',
    '      letter-spacing: 0.08em;',
    '      text-transform: uppercase;',
    '      color: var(--text-muted);',
    '      margin: 1.4rem 0 0.5rem;',
    '      padding-left: 0.5rem;',
    '    }',

    '    .nav-group-label:first-child { margin-top: 0; }',

    '    nav ul { list-style: none; }',

    '    nav li a {',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 0.5rem;',
    '      padding: 0.42rem 0.5rem;',
    '      color: var(--text-muted);',
    '      text-decoration: none;',
    '      font-size: 0.82rem;',
    '      border-radius: 6px;',
    '      transition: color .15s, background .15s;',
    '    }',

    '    nav li a:hover { color: var(--text); background: var(--surface-2); }',

    '    nav li a.active {',
    '      color: #fff;',
    '      background: rgba(124,106,255,.15);',
    '      font-weight: 500;',
    '    }',

    '    .nav-method {',
    '      font-size: 0.55rem;',
    '      font-weight: 700;',
    '      padding: 0.1rem 0.35rem;',
    '      border-radius: 4px;',
    '      letter-spacing: 0.04em;',
    '      flex-shrink: 0;',
    '    }',

    '    .nm-get  { background: var(--get-bg);  color: var(--get); }',
    '    .nm-post { background: var(--post-bg); color: var(--post); }',

    // ── Main ───────────────────────────────────────────────────────────────
    '    main {',
    '      flex: 1;',
    '      margin-left: var(--sidebar-w);',
    '      padding: 3rem clamp(1.5rem, 6vw, 5rem);',
    '      max-width: 900px;',
    '      width: 100%;',
    '    }',

    '    .content-section { display: none; animation: fadeIn .3s ease; }',
    '    .content-section.active { display: block; }',

    '    @keyframes fadeIn {',
    '      from { opacity: 0; transform: translateY(8px); }',
    '      to   { opacity: 1; transform: translateY(0); }',
    '    }',

    // ── Typography ─────────────────────────────────────────────────────────
    '    .content-section h1 {',
    '      font-size: 2rem;',
    '      font-weight: 700;',
    '      letter-spacing: -0.03em;',
    '      line-height: 1.2;',
    '      margin-bottom: 0.6rem;',
    '      background: linear-gradient(135deg, #e2e8f0 30%, #94a3b8);',
    '      -webkit-background-clip: text;',
    '      -webkit-text-fill-color: transparent;',
    '    }',

    '    .content-section h2 {',
    '      font-size: 1.35rem;',
    '      font-weight: 600;',
    '      margin: 2.5rem 0 1rem;',
    '      padding-bottom: 0.65rem;',
    '      border-bottom: 1px solid var(--border);',
    '      color: #fff;',
    '      letter-spacing: -0.02em;',
    '    }',

    '    .content-section h3 {',
    '      font-size: 1rem;',
    '      font-weight: 600;',
    '      margin: 1.75rem 0 0.5rem;',
    '      color: var(--text-dim);',
    '    }',

    '    .content-section p {',
    '      color: var(--text-muted);',
    '      margin-bottom: 1rem;',
    '      font-size: 0.92rem;',
    '    }',

    '    .content-section ul, .content-section ol {',
    '      padding-left: 1.4rem;',
    '      margin-bottom: 1rem;',
    '    }',

    '    .content-section li {',
    '      color: var(--text-muted);',
    '      font-size: 0.92rem;',
    '      margin-bottom: 0.3rem;',
    '    }',

    '    .content-section hr {',
    '      border: none;',
    '      border-top: 1px solid var(--border-soft);',
    '      margin: 2rem 0;',
    '    }',

    '    .content-section a { color: var(--primary); text-decoration: none; }',
    '    .content-section a:hover { text-decoration: underline; }',

    '    .content-section blockquote {',
    '      margin: 1.2rem 0;',
    '      padding: 0.8rem 1.2rem;',
    '      border-left: 3px solid var(--primary);',
    '      background: rgba(124,106,255,.07);',
    '      border-radius: 0 var(--radius) var(--radius) 0;',
    '      font-size: 0.88rem;',
    '      color: var(--text-dim);',
    '    }',

    // ── Code ───────────────────────────────────────────────────────────────
    '    .content-section code {',
    '      font-family: "JetBrains Mono", monospace;',
    '      font-size: 0.82em;',
    '      background: var(--surface-2);',
    '      padding: 0.15em 0.4em;',
    '      border-radius: 4px;',
    '      color: #c084fc;',
    '    }',

    '    .code-wrap {',
    '      position: relative;',
    '      margin: 1.25rem 0;',
    '    }',

    '    .code-wrap pre {',
    '      background: var(--code-bg) !important;',
    '      padding: 1.25rem 1.5rem !important;',
    '      border-radius: var(--radius) !important;',
    '      border: 1px solid var(--border) !important;',
    '      overflow-x: auto;',
    '      font-family: "JetBrains Mono", monospace !important;',
    '      font-size: 0.8rem !important;',
    '      line-height: 1.6 !important;',
    '      scrollbar-width: thin;',
    '      scrollbar-color: var(--border) transparent;',
    '    }',

    '    .code-wrap pre code {',
    '      background: transparent !important;',
    '      padding: 0 !important;',
    '      color: inherit;',
    '      font-size: inherit;',
    '    }',

    '    .copy-btn {',
    '      position: absolute;',
    '      top: 0.6rem; right: 0.6rem;',
    '      background: var(--surface-2);',
    '      border: 1px solid var(--border);',
    '      color: var(--text-muted);',
    '      border-radius: 6px;',
    '      padding: 0.3rem 0.6rem;',
    '      font-size: 0.7rem;',
    '      font-family: "Inter", sans-serif;',
    '      cursor: pointer;',
    '      transition: all .15s;',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 0.3rem;',
    '    }',

    '    .copy-btn:hover { background: var(--border); color: var(--text); }',
    '    .copy-btn.copied { color: var(--post); border-color: rgba(74,222,128,.4); }',

    // ── Table ──────────────────────────────────────────────────────────────
    '    .content-section table {',
    '      width: 100%;',
    '      border-collapse: collapse;',
    '      margin: 1.25rem 0;',
    '      font-size: 0.85rem;',
    '      border: 1px solid var(--border);',
    '      border-radius: var(--radius);',
    '      overflow: hidden;',
    '    }',

    '    .content-section th {',
    '      text-align: left;',
    '      background: var(--surface-2);',
    '      padding: 0.65rem 1rem;',
    '      border-bottom: 1px solid var(--border);',
    '      color: var(--text-dim);',
    '      font-weight: 600;',
    '      font-size: 0.78rem;',
    '      text-transform: uppercase;',
    '      letter-spacing: 0.04em;',
    '    }',

    '    .content-section td {',
    '      padding: 0.65rem 1rem;',
    '      border-bottom: 1px solid var(--border-soft);',
    '      color: var(--text-muted);',
    '      vertical-align: top;',
    '    }',

    '    .content-section tr:last-child td { border-bottom: none; }',

    // ── Method badges ──────────────────────────────────────────────────────
    '    .method-badge {',
    '      display: inline-flex;',
    '      align-items: center;',
    '      gap: 0.5rem;',
    '      padding: 0.35rem 0.85rem;',
    '      border-radius: 6px;',
    '      font-family: "JetBrains Mono", monospace;',
    '      font-size: 0.78rem;',
    '      font-weight: 600;',
    '      margin-bottom: 0.5rem;',
    '    }',

    '    .mb-get  { background: var(--get-bg);  color: var(--get);  border: 1px solid rgba(56,189,248,.25); }',
    '    .mb-post { background: var(--post-bg); color: var(--post); border: 1px solid rgba(74,222,128,.25); }',

    // ── Hero strip at top of section ───────────────────────────────────────
    '    .doc-hero {',
    '      padding: 1.5rem 1.75rem;',
    '      background: linear-gradient(135deg, rgba(124,106,255,.08), rgba(192,132,252,.04));',
    '      border: 1px solid var(--border);',
    '      border-radius: var(--radius);',
    '      margin-bottom: 2rem;',
    '    }',

    '    .doc-hero p { margin: 0; font-size: 0.9rem; color: var(--text-muted); }',

    // ── Base URL pill ──────────────────────────────────────────────────────
    '    .base-url-strip {',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 0.75rem;',
    '      background: var(--code-bg);',
    '      border: 1px solid var(--border);',
    '      border-radius: var(--radius);',
    '      padding: 0.7rem 1rem;',
    '      margin: 1rem 0 2rem;',
    '      font-family: "JetBrains Mono", monospace;',
    '      font-size: 0.8rem;',
    '      overflow-x: auto;',
    '    }',

    '    .base-url-label {',
    '      font-size: 0.65rem;',
    '      font-weight: 700;',
    '      text-transform: uppercase;',
    '      letter-spacing: 0.06em;',
    '      color: var(--text-muted);',
    '      flex-shrink: 0;',
    '    }',

    '    .base-url-value { color: var(--primary); }',

    // ── Responsive ────────────────────────────────────────────────────────
    '    @media (max-width: 800px) {',
    '      aside { width: 100%; height: auto; position: relative; border-right: none; border-bottom: 1px solid var(--border); }',
    '      main  { margin-left: 0; padding: 2rem 1.25rem; max-width: 100%; }',
    '      body  { flex-direction: column; }',
    '    }',

    '  </style>',
    '</head>',
    '<body>',

    // ── Sidebar ────────────────────────────────────────────────────────────
    '<aside>',
    '  <div class="sidebar-header">',
    '    <div class="brand">',
    '      <div class="brand-icon">✦</div>',
    '      <div>',
    '        <div class="brand-name">Fashion Redemption</div>',
    '        <div class="brand-sub">API Documentation</div>',
    '      </div>',
    '    </div>',
    '    <div class="version-badge"><span class="version-dot"></span>v1 · Production</div>',
    '  </div>',

    '  <div class="sidebar-search">',
    '    <div class="search-box">',
    '      <span class="search-icon">⌕</span>',
    '      <input id="doc-search" type="text" placeholder="Search docs..." autocomplete="off">',
    '    </div>',
    '  </div>',

    '  <nav class="sidebar-nav">',
    '    <p class="nav-group-label">Getting Started</p>',
    '    <ul>',
    '      <li><a href="#" class="nav-link active" data-section="product-api" data-anchor="overview">Overview</a></li>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="authentication">Authentication</a></li>',
    '    </ul>',

    '    <p class="nav-group-label">GET Endpoints</p>',
    '    <ul>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="get-products"><span class="nav-method nm-get">GET</span> Get Products</a></li>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="get-product-details"><span class="nav-method nm-get">GET</span> Product Details</a></li>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="search-products"><span class="nav-method nm-get">GET</span> Search Products</a></li>',
    '    </ul>',

    '    <p class="nav-group-label">POST Endpoints</p>',
    '    <ul>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="chatbot-product-query"><span class="nav-method nm-post">POST</span> Chatbot Query</a></li>',
    '    </ul>',

    '    <p class="nav-group-label">AI Integration</p>',
    '    <ul>',
    '      <li><a href="#" class="nav-link" data-section="ai-integration" data-anchor="">Integration Guide</a></li>',
    '      <li><a href="#" class="nav-link" data-section="ai-integration" data-anchor="ai-tool-definition-json-schema">Tool Schema</a></li>',
    '      <li><a href="#" class="nav-link" data-section="ai-integration" data-anchor="advanced-filtering-examples">Filter Examples</a></li>',
    '    </ul>',

    '    <p class="nav-group-label">Reference</p>',
    '    <ul>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="security-practices">Security</a></li>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="rate-limits">Rate Limits</a></li>',
    '      <li><a href="#" class="nav-link" data-section="product-api" data-anchor="best-practices">Best Practices</a></li>',
    '    </ul>',
    '  </nav>',
    '</aside>',

    // ── Main ───────────────────────────────────────────────────────────────
    '<main>',
    '  <div id="product-api"  class="content-section active"></div>',
    '  <div id="ai-integration" class="content-section"></div>',
    '</main>',

    // ── Hidden content stores (base64) ─────────────────────────────────────
    '<div id="product-docs-raw"  style="display:none">' + Buffer.from(productDocs).toString('base64') + '</div>',
    '<div id="ai-docs-raw"       style="display:none">' + Buffer.from(aiDocs).toString('base64') + '</div>',

    // ── Script ─────────────────────────────────────────────────────────────
    '<script>',

    // Render markdown
    '(function() {',
    '  const productRaw = atob(document.getElementById("product-docs-raw").innerText.trim());',
    '  const aiRaw      = atob(document.getElementById("ai-docs-raw").innerText.trim());',

    '  marked.setOptions({ gfm: true, breaks: false });',

    '  document.getElementById("product-api").innerHTML     = marked.parse(productRaw);',
    '  document.getElementById("ai-integration").innerHTML  = marked.parse(aiRaw);',
    '',
    '  // Dynamically assign anchor IDs to all headings',
    '  document.querySelectorAll(".content-section h1, .content-section h2, .content-section h3").forEach(h => {',
    '    const text = h.textContent.toLowerCase()',
    '      .replace(/^\\d+\\.\\s*/, "")',
    '      .replace(/[^a-z0-9\\s-]/g, "")',
    '      .trim()',
    '      .replace(/\\s+/g, "-");',
    '    h.id = text;',
    '  });',

    // Wrap all <pre> blocks with .code-wrap + copy button
    '  document.querySelectorAll("pre").forEach(pre => {',
    '    const wrap = document.createElement("div");',
    '    wrap.className = "code-wrap";',
    '    pre.parentNode.insertBefore(wrap, pre);',
    '    wrap.appendChild(pre);',

    '    const btn = document.createElement("button");',
    '    btn.className = "copy-btn";',
    '    btn.innerHTML = "⧉ Copy";',
    '    btn.addEventListener("click", () => {',
    '      const text = pre.querySelector("code")?.innerText || pre.innerText;',
    '      navigator.clipboard.writeText(text).then(() => {',
    '        btn.textContent = "✓ Copied";',
    '        btn.classList.add("copied");',
    '        setTimeout(() => { btn.innerHTML = "⧉ Copy"; btn.classList.remove("copied"); }, 1800);',
    '      });',
    '    });',
    '    wrap.appendChild(btn);',
    '  });',

    // Add method badges before <h3> that contain endpoint pattern
    '  document.querySelectorAll(".content-section h3").forEach(h3 => {',
    '    const text = h3.textContent;',
    '    if (/^\\d+\\.\\s*(get|post|patch|delete|put)/i.test(text)) {',
    '      const method = text.match(/\\b(GET|POST|PATCH|DELETE|PUT)\\b/i)?.[1]?.toUpperCase();',
    '      if (method) {',
    '        const badge = document.createElement("span");',
    '        badge.className = "method-badge mb-" + method.toLowerCase();',
    '        badge.textContent = method;',
    '        h3.parentNode.insertBefore(badge, h3);',
    '      }',
    '    }',
    '  });',

    // Re-run Prism highlighting
    '  if (window.Prism) Prism.highlightAll();',

    // Navigation
    '  const navLinks = document.querySelectorAll(".nav-link");',
    '  const sections = document.querySelectorAll(".content-section");',

    '  function activateSection(sectionId) {',
    '    sections.forEach(s => s.classList.remove("active"));',
    '    const target = document.getElementById(sectionId);',
    '    if (target) target.classList.add("active");',
    '  }',

    '  navLinks.forEach(link => {',
    '    link.addEventListener("click", e => {',
    '      e.preventDefault();',
    '      const sectionId = link.dataset.section;',
    '      const anchor    = link.dataset.anchor;',

    '      navLinks.forEach(l => l.classList.remove("active"));',
    '      link.classList.add("active");',

    '      activateSection(sectionId);',

    '      if (anchor) {',
    '        setTimeout(() => {',
    '          const el = document.getElementById(anchor);',
    '          if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });',
    '          else window.scrollTo({ top: 0, behavior: "smooth" });',
    '        }, 50);',
    '      } else {',
    '        window.scrollTo({ top: 0, behavior: "smooth" });',
    '      }',
    '    });',
    '  });',

    // Doc search — highlights matching headings
    '  const searchInput = document.getElementById("doc-search");',
    '  searchInput.addEventListener("input", () => {',
    '    const q = searchInput.value.toLowerCase().trim();',
    '    if (!q) {',
    '      document.querySelectorAll(".content-section h2, .content-section h3").forEach(h => h.style.outline = "");',
    '      return;',
    '    }',
    '    let first = null;',
    '    document.querySelectorAll(".content-section h2, .content-section h3").forEach(h => {',
    '      if (h.textContent.toLowerCase().includes(q)) {',
    '        h.style.outline = "2px solid var(--primary)";',
    '        h.style.outlineOffset = "4px";',
    '        h.style.borderRadius = "4px";',
    '        if (!first) first = h;',
    '      } else {',
    '        h.style.outline = "";',
    '      }',
    '    });',
    '    if (first) {',
    '      const parentSection = first.closest(".content-section");',
    '      if (parentSection) {',
    '        activateSection(parentSection.id);',
    '        navLinks.forEach(l => l.classList.remove("active"));',
    '      }',
    '      setTimeout(() => first.scrollIntoView({ behavior: "smooth", block: "center" }), 60);',
    '    }',
    '  });',

    '})();',
    '</script>',

    '</body>',
    '</html>'
  ];

  return parts.join('\n');
};
